name: Pylint

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Run Python commands
        run: |
          pip install --upgrade pip
          python3.8 -m venv env
          source env/bin/activate
          pylint --disable=import-error,redefined-outer-name,broad-exception-caught,invalid-name,unused-import,no-member,no-self-argument $(git ls-files '*.py')
